[build]
  publish = "dist/main"
  # Vous pouvez chaîner vos commandes de build ici
  command = "npm run build:all"

[build.environment]
  # 3. Cette variable dit à Netlify de ne pas essayer de deviner le projet
  # et de juste exécuter la commande ci-dessus.
  ANGULAR_PROJECT = "main"
